### ISSUE TITLE
Line 37 foreach::foreach

### ISSUE THREAD

**Issue by jielab** [mkiang/airline_testing_strategies#3]
Dear Mathew:

Congratulations on a very nice paper, and thanks for making the R code available!

I have a couple of questions on your R code. I would deeply appreciate if you could clarify.

1. You used **foreach::foreach(i = sample(1:NROW(param_grid))) %dopar% {** a few times. Why put **sample()** here? Cann't we simply use **foreach::foreach(i = 1:NROW(param_grid)) %dopar% {**? 

2. Within your foreach loop, I added **print(paste("NOW BEGIN", i)** right at the beginning of the loop **{**, and **print(paste("NOW FINISH", i)** right before the end of the loop **}**. Surprisingly, the two **i** printed out are different... How could this be? Previously, I have been using the tradtional **for (i in 1:nrow(dat))** approach. Can I change your **foreach::foreach** to **for (i in 1:nrow(param_grid))**?  

3. How to check that your second script **02_run_main_simulations.R** is finished successfully? Of course, first there is no error message in **02_run_main_simulations.Rout**.

Thank you very much & best regards,
Jie

**Comment by mkiang** [comment]
Hello, I am leaving issues open for people to identify mistakes in the code. It's not really designed to answer questions about (correctly functioning) code so I am going to close it.

Briefly, to answer your questions:

1. Yes, you can use 1:NROW().
2. foreach is not a for loop. It is more like an apply. It does things on different cores so it does not (by default) return information to the console. The scripts are designed to be run on a cluster and not to be run interactively. Yes, you can switch to a normal for loop but you will lose the parallelization and results will likely take a very long time.
3. Again, this is not designed to be run interactively. If you let it run through and there are no errors, then it is done. 

I suggest reading up about foreach by running `vignette("foreach")`. A lot of this seems to be due to misunderstanding of how it is designed to be run.

**Comment by jielab** [comment]
Dear Mathew:

Thank you very much for your clarification! I now read 
`vignette("foreach")` and understood that it is a great way for parallel processing.

I do still want to make sure that I got it right. I will appreciate again if you could quickly reply to my below questions.

1. So, you mean that I could change your code **foreach(i = sample(1:NROW(param_grid)))**  to **foreach(i = 1:NROW(param_grid))** and it won't affect any analysis output?

2. Since there are multiple **foreach** in your script, would it be better that I use **stopCluster(A-NAME)** , instead of using **stopImplicitCluster()**, at the end of each loop?

3. Can I still use foreach to print out **i** correctly, shown as below? I do need to make sure that the analysis result of **person i** is labelled as person i, instead of j. 
```
foreach(i = c(“person-A”, ”person-B”, ”person-C”)) %dopar% {
   … ## RUN something
   print(paste(i, "person analyzed successfully"))
}
```

I will stop asking "easy" questions like this.

Best regards,
Jie

**Comment by mkiang** [comment]
1. Yes. You can do whatever you want. I sample because it spreads tasks across different CPUs on the server (which have different speeds) but you do not need to.
2. You can create a cluster and stop it if you want. It shouldn't matter if you only have one primary node. 
3. I do not know how to print output from foreach. Again, it is not a for-loop — it is sending jobs to other cores. Your prints are printing but they are printing in different cores that you cannot see (since you can only see the primary node). 

If you identify technical issues with the code or mistakes, I am happy to take a look but I am going to lock this conversation because this isn't really a forum for answering questions about how foreach works and not how I intend to use it. 

Good luck!
